esphome:
  name: c6
  friendly_name: c6

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

external_components:
  source: github://kivinen/i2c_dimmer_4ch

# Enable logging
logger:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True
  id: bus_main

light:
  - platform: i2c_dimmer_4ch
    name: "test"
    channel: 131
    i2c_id: bus_main
    address: 0x3f
    gamma_correct: 1.0
    max_value: 90
    min_value: 0

# Output section is mandatory even if it is empty to get output/float_output.h
output:

