esphome:
  name: c6
  friendly_name: c6

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

external_components:
  source: github://kivinen/i2c_dimmer_4ch

# Enable logging
logger:
#  level: VERBOSE

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True
  id: bus_main

# 4 Channel Dimmer has four channels numbered from 128 to 131
#
# The min and max values limit the actual values sent to the dimmer
# value 100 = off, value = 0 is fully on, limiting max value will
# allow keeping led lights on, as when the light is dimmed too much
# there is not enough power to keep led light drivers running and they
# will shut down completely (or start blinking or some of them turn
# off and some stay dim etc). This is not needed if using incandescent
# light bulbs.
#
# Even if the max value is set to some value, when light is turned
# off, then value 100 is sent to the dimmer.

light:
  - platform: i2c_dimmer_4ch
    id: dimmer1
    name: "test"
    channel: 131
    i2c_id: bus_main
    address: 0x3f
    # gamma_correct: 1.0
    max_value: 90
    min_value: 0
    default_transition_length: 500ms
    effects:
      - pulse:
          transition_length: 500ms
          update_interval: 500ms
          max_brightness: 1.0
          min_brightness: 0.3

# Output section is mandatory even if it is empty to get
# output/float_output.h
output:

# Here is example of one button light control
#
# Short click on the button will toggle light on and off remembering
# previous brightness
#
# Long click will start adjusting brightness brightness will increase
# until it is at max, and then it will start decreasing until it in
# min, and then it starts increasing again.

#
# dim_dir_up specifies the direction of the brightness adjustment
# dim_last_brightness contains the brightness before light was turned
# off, and is used to restore the brightness
#
globals:
  - id: dim_dir_up
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: dim_last_brightness
    type: float
    restore_value: no
    initial_value: '1.0'

# 
# This uses only one button to adjust the brightness
#
# It uses on_multi_click to do everything. The first it will detect
# double click, i.e., and if so turn the light to full brightness.
#
# The next timing detects short click, which will toggle the light on
# or off. When it turns light off it will store the previous
# brightness level to dim_last_brightness global, and when it turns it
# back on it restores that level. 
#
# The final timing detects long press (more than 0.5 seconds), and
# that will start adjusting brightness of the light. The light level
# will go to one direction until it hits the max or min level and then
# it lingers there for a moment, before starting to go to the another
# direction. Every time you start long press the direction changes,
# which makes it easy to adjust exact level, i.e., if you overshoot
# the level you simply release the button and do a long press again to
# go back. 
#
# Inside the loop it uses if statement to check the value of
# dim_dir_up and adjust the light level relatively based on that.
# Note, that the relative_brightness can't use !lambda
# id(dimmer1).remote_values,get_brightness(); as if there is lambda in
# the light.dim_relative then the next delay between
# light.dim_relative does not work. 
#
binary_sensor:
  - platform: gpio
    id: in1
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
    filters:
      - invert:   
      - delayed_on_off: 10ms
      - settle: 10ms
    on_multi_click:
    - timing:
        - ON for at most 350ms
        - OFF for at most 500ms
        - ON for at most 350ms
        - OFF for at least 100ms
      then:
        - logger.log: "Double click"
        - light.turn_on: 
            id: dimmer1
            brightness: 100%
    - timing:
        - ON for at most 350ms
        - OFF for at least 100ms
      then:
        - logger.log: "Click"
        - if:
            condition:
              light.is_on: dimmer1
            then:
              - lambda: |-
                  id(dim_last_brightness) = id(dimmer1).remote_values.get_brightness();
              - light.turn_off: dimmer1
            else:
              - light.turn_on:
                  id: dimmer1
                  brightness: !lambda return id(dim_last_brightness);
    - timing:
        - ON for at least 500ms
      then:
        - logger.log: "Brightness adjustment"
        - while:
            condition:
              binary_sensor.is_on: in1
            then:
              - if:
                  condition:
                    lambda: return(id(dim_dir_up));
                  then:
                    - light.dim_relative:
                        id: dimmer1
                        relative_brightness: 5%
                        transition_length: 100ms
                        brightness_limits:
                          max_brightness: 100%
                          min_brightness: 10%
                  else:
                    - light.dim_relative:
                        id: dimmer1
                        relative_brightness: -5%
                        transition_length: 100ms
                        brightness_limits:
                          max_brightness: 100%
                          min_brightness: 10%
              - delay: 100ms
              - if:
                  condition:
                    lambda: |-
                      return (id(dimmer1).remote_values.get_brightness() > 0.99);
                  then:
                    - delay: 200ms
                    - lambda: id(dim_dir_up) = false;
                    - logger.log: "Direction down"
              - if: 
                  condition:
                    lambda: |-
                      return (id(dimmer1).remote_values.get_brightness() < 0.11);
                  then:
                    - delay: 200ms
                    - lambda: id(dim_dir_up) = true;
                    - logger.log: "Direction up"
        - lambda: id(dim_dir_up) = (id(dim_dir_up) == false);
    - timing:
        - ON for 350ms to 1000ms
        - OFF for at most 500ms
        - ON for at least 50ms
        - OFF for at most 500ms
        - ON for at least 50ms
        - OFF for at most 500ms
        - ON for at least 50ms
        - OFF for at least 100ms
      then:
        - logger.log: "Morse B detected enable blink"
        - light.turn_on:
            id: dimmer1
            effect: pulse
