esphome:
  name: c6
  friendly_name: c6

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

external_components:
  source: github://kivinen/i2c_dimmer_4ch

# Enable logging
logger:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True
  id: bus_main

# 4 Channel Dimmer has four channels numbered from 128 to 131
#
# The min and max values limit the actual values sent to the dimmer
# value 100 = off, value = 0 is fully on, limiting max value 
# will allow keeping led lights on, as when the light is dimmed
# too much there is not enough power to keep led light drivers
# running and they will shut down completely (or start blinking
# or some of them turn off and some stay dim etc). This is not
# needed if using incandescent light bulbs.
#
# Even if the max value is set to some value, when light
# is turned off, then value 100 is sent to the dimmer.

light:
  - platform: i2c_dimmer_4ch
    id: dimmer1
    name: "test"
    channel: 131
    i2c_id: bus_main
    address: 0x3f
    # gamma_correct: 1.0
    max_value: 90
    min_value: 0
    default_transition_length: 500ms

# Output section is mandatory even if it is empty to get
# output/float_output.h
output:

# Here is example of one button light control
#
# Short click on the button will toggle light on and off
# remembering previous brightness
#
# Long click will start adjusting brightness
# brightness will increase until it is at max, and then it will
# start decreasing until it in min, and then it starts
# increasing again.

#
# dim_dir_up specifies the direction of the brightness adjustment
# dim_last_brightness contains the brightness before light was turned
# off, and is used to restore the brightness
#
globals:
  - id: dim_dir_up
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: dim_last_brightness
    type: float
    restore_value: no
    initial_value: '1.0'

# 
# This uses only one button to adjust the brightness
#
# It uses on_click action turn light on and off.
# If the click is longer than 30ms but less than 350ms
# then it checks wheter light is on, and if so it  stores the
# dim_last_brightness and turns light off. It the light is off,
# it will turn it on with specified brightness
#
# The brightness adjustment is done using on_press, which
# first delays for 0.5 seconds, and then checks whether
# button is still pressed. If so it will loop as long as the
# button is pressed. When the button is released the direction
# is also changed.
#
# Inside the loop it uses if statement to check the value of
# dim_dir_up and adjust the light level relatively based on that.
# Note, that the relative_brightness can't use
# !lambda id(dimmer1).remote_values,get_brightness();
# as if there is lambda in the light.dim_relative then the next
# delay between light.dim_relative does not work.
# After adjusting brightness it will delay for 100ms, and then chec
# whether we are in max or min brightness and if so, then it will
# delay for a extra 200ms, and then change direction. This makes
# it easier to use max or min brightness.
#
binary_sensor:
  - platform: gpio
    id: in1
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
    filters:
      - invert:   
      - delayed_on_off: 30ms
      - settle: 30ms
    on_multi_click:
    - timing:
        - ON for at most 350ms
        - OFF for at most 500ms
        - ON for at most 350ms
        - OFF for at least 100ms
      then:
        - logger.log: "Double click"
        - light.turn_on: 
            id: dimmer1
            brightness: 100%
    - timing:
        - ON for at most 350ms
        - OFF for at least 100ms
      then:
        - logger.log: "Click"
        - if:
            condition:
              light.is_on: dimmer1
            then:
              - lambda: |-
                  id(dim_last_brightness) = id(dimmer1).remote_values.get_brightness();
              - light.turn_off: dimmer1
            else:
              - light.turn_on:
                  id: dimmer1
                  brightness: !lambda return id(dim_last_brightness);
    - timing:
        - ON for at least 500ms
      then:
        - logger.log: "Brightness adjustment"
        - while:
            condition:
              binary_sensor.is_on: in1
            then:
              - if:
                  condition:
                    lambda: return(id(dim_dir_up));
                  then:
                    - light.dim_relative:
                        id: dimmer1
                        relative_brightness: 5%
                        transition_length: 100ms
                        brightness_limits:
                          max_brightness: 100%
                          min_brightness: 10%
                  else:
                    - light.dim_relative:
                        id: dimmer1
                        relative_brightness: -5%
                        transition_length: 100ms
                        brightness_limits:
                          max_brightness: 100%
                          min_brightness: 10%
              - delay: 100ms
              - if:
                  condition:
                    lambda: |-
                      return (id(dimmer1).remote_values.get_brightness() > 0.99);
                  then:
                    - delay: 200ms
                    - lambda: id(dim_dir_up) = false;
                    - logger.log: "Direction down"
              - if: 
                  condition:
                    lambda: |-
                      return (id(dimmer1).remote_values.get_brightness() < 0.11);
                  then:
                    - delay: 200ms
                    - lambda: id(dim_dir_up) = true;
                    - logger.log: "Direction up"
        - lambda: id(dim_dir_up) = (id(dim_dir_up) == false);
